config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # 単体のページ
  root "static_pages#top"
  get "how_to_use", to: "static_pages#how_to_use"
  get "develop", to: "static_pages#develop"
  get "ogp", to: "static_pages#ogp"
  get "contact", to: "static_pages#contact"
  get "terms_of_service", to: "static_pages#terms_of_service"
  get "privacy_policy", to: "static_pages#privacy_policy"
  get "release_note", to: "static_pages#release_note"

  # ユーザー関連
  resources :users, only: %i[new create destroy]
  
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  post "oauth/callback", to: "oauths#callback" # サービスによってGETとPOSTが異なる場合があるので両方作成
  get "oauth/callback", to: "oauths#callback"
  get "oauth/request/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :profile, only: [:show, :edit, :update], path: 'mypage'  # パスを /mypage, /mypage/edit に
  
  resources :password_resets, only: %i[new create edit update]


  # グラフ作成メイン画面
  get "canvas", to: "canvas#index"
  
  # マイグラフ・マイテンプレート・都市
  resources :graphs, only: %i[index show edit update destroy]
  resources :templates, only: %i[index destroy]
  resources :cities, only: %i[index]

  # API
  namespace :api do
    resources :graphs, only: %i[index show create]
    resources :templates, only: %i[index show create]
    resources :cities, only: %i[index show]
    get "check_login", to: "user_sessions#check_login"
    post "download_counts", to: "download_counts#create"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :require_login
  skip_before_action :check_profile, only: [:edit, :update]

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to profile_path, success: "プロフィールを更新しました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :occupation)
  end

  # 追々，Concernを使って共通化する
  def not_authenticated
    redirect_to login_path, error: "ログインが必要です"
  end
end

app/views/profiles/edit.html.slim
- set_meta_tags title: 'ユーザー登録情報変更'

.container.mx-auto.max-w-md.my-10
    .w-full
      h1.text-3xl.font-bold
        | ユーザー登録情報変更
    
      .my-10
        = form_with model: @user, url: profile_path ,local: true do |f|
          - if @user.errors.any?
            div.alert.alert-error.font-bold
              ul
                - @user.errors.full_messages.each do |message|
                  li
                    = message

          .my-10.space-y-3
            = f.label :username, class: 'text-xl font-bold'
            = f.text_field :username, class: 'w-full input input-borderd input-primary'
          
          .my-10.space-y-3
            = f.label :email, class: 'text-xl font-bold'
            - if @user.authentications.empty?
              = f.email_field :email, class: 'w-full input input-borderd input-primary'
            - else
              .w-full.text-lg
                = @user.email
              .px-2.py-1.inline-flex.items-center.gap-2.border.border-gray-500.rounded-md.text-slate-700.bg-white
                img class="w-4 h-4" src="https://www.svgrepo.com/show/475656/google-color.svg" loading="lazy" alt="google logo"
                span.text-sm Googleアカウント利用中


          .my-10.space-y-3
            = f.label :occupation, class: 'text-xl font-bold'
            = f.select :occupation, User.occupations.keys.map { |k| [t("enum.user.occupation.#{k}"), k] }, { prompt: "選択して下さい" }, class: 'w-full select select-bordered select-primary'

          .mt-20.flex.justify-center.gap-20
            = link_to '戻る', profile_path, class: 'btn'
            = f.submit class: 'btn btn-primary'

app/views/profiles/show.html.slim
- set_meta_tags title: 'マイページ'

.container.mx-auto.max-w-md.my-10
  .w-full
    h1.text-3xl.font-bold
      | マイページ
  
    .my-10
      .my-8.space-y-3
        .text-lg.text-xl.font-bold
          | ユーザーネーム
        .w-full.text-lg
          = @user.username
      
      .my-10.space-y-3
        .text-lg.text-xl.font-bold
          | メールアドレス
        .w-full.text-lg
          = @user.email
        - if @user.authentications.present?
          .px-2.py-1.inline-flex.items-center.gap-2.border.border-gray-500.rounded-md.text-slate-700.bg-white
            img class="w-4 h-4" src="https://www.svgrepo.com/show/475656/google-color.svg" loading="lazy" alt="google logo"
            span.text-sm Googleアカウント利用中

      .my-10.space-y-3
        .text-lg.text-xl.font-bold
          | 職業・学年
        .w-full.text-lg
          = t("enum.user.occupation.#{@user.occupation}")
    
    .mt-15.flex.justify-center.gap-20
      = link_to '変更する', edit_profile_path, class: 'btn btn-primary'
      = link_to 'パスワード再設定', new_password_reset_path, class: 'btn btn-primary btn-warning'
    .mt-10.flex.justify-end
      = link_to "▶ ログアウト", logout_path, data: { turbo_method: :delete }, class: "font-bold btn btn-ghost btn-sm"

    .mt-5.flex.justify-end
      button.btn.btn-sm.btn-ghost onclick="my_modal_4.showModal()" ▶ユーザーを削除

    / 退会モーダル
    dialog#my_modal_4.modal
      .modal-box.max-w-2xl
        h3.font-bold.text-xl
          | 本当にユーザーを削除しますか？
        .p-5
          p.py-4
            | 次の情報は<strong>完全に削除</strong>されます。
            ul.list-disc.ml-5.space-y-3
              li
                | 全てのユーザー情報
              li
                | 保存したマイグラフ
              li
                | 保存したマイテンプレート
          
          p.py-4 
            | これらの情報は<strong>復元できません</strong>ので、ご注意ください。

        .modal-action.justify-center
          form method="dialog"
            .flex.justify-center.space-x-20
              button.btn
                | キャンセル

              = link_to "ユーザー削除を実行", user_path(@user), method: :delete, data: { turbo_method: :delete }, class: "btn btn-error" 