config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # 単体のページ
  root "static_pages#top"
  get "how_to_use", to: "static_pages#how_to_use"
  get "develop", to: "static_pages#develop"
  get "ogp", to: "static_pages#ogp"
  get "contact", to: "static_pages#contact"
  get "terms_of_service", to: "static_pages#terms_of_service"
  get "privacy_policy", to: "static_pages#privacy_policy"
  get "release_note", to: "static_pages#release_note"

  # ユーザー関連
  resources :users, only: %i[new create destroy]
  
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  post "oauth/callback", to: "oauths#callback" # サービスによってGETとPOSTが異なる場合があるので両方作成
  get "oauth/callback", to: "oauths#callback"
  get "oauth/request/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :profile, only: [:show, :edit, :update], path: 'mypage'  # パスを /mypage, /mypage/edit に
  
  resources :password_resets, only: %i[new create edit update]


  # グラフ作成メイン画面
  get "canvas", to: "canvas#index"
  
  # マイグラフ・マイテンプレート・都市
  resources :graphs, only: %i[index show edit update destroy]
  resources :templates, only: %i[index destroy]
  resources :cities, only: %i[index]

  # API
  namespace :api do
    resources :graphs, only: %i[index show create]
    resources :templates, only: %i[index show create]
    resources :cities, only: %i[index show]
    get "check_login", to: "user_sessions#check_login"
    post "download_counts", to: "download_counts#create"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/graph.rb
class Graph < ApplicationRecord
  belongs_to :user
  belongs_to :city
  has_one :graph_setting, as: :metadata, dependent: :destroy

  mount_uploader :thumbnail, GraphThumbnailUploader

  validates :user_id, presence: true
  validates :city_id, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :note, length: { maximum: 65_535 }

  def self.ransackable_attributes(auth_object = nil)
    %w[title note created_at updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[city]
  end
end

app/controllers/api/graphs_controller.rb
class Api::GraphsController < Api::BaseController
  # GET /api/graphs
  # テスト表示用
  def index
    graphs = current_user.graphs.all
    render json: { current_user: current_user, graphs: graphs }
  end

  # GET /api/graphs/:id
  def show
    graph = current_user.graphs.find(params[:id])
    render json: { graph: graph, graph_setting: graph.graph_setting }
  end

  # POST /api/graphs
  def create
    graph = current_user.graphs.new(graph_params.except(:thumbnail_url, :graph_setting))
    graph.thumbnail_data_uri = graph_params[:thumbnail_url]  # gem 'carrierwave-data-uri'のメソッドで画像データを投入
    graph_setting = graph.build_graph_setting(settings: graph_params[:graph_setting])
    
    ActiveRecord::Base.transaction do
      graph.save!
      graph_setting.save!
      render json: { graph: graph, graph_setting: graph_setting }, status: :ok
    end
  rescue ActiveRecord::RecordInvalid => e
    logger.error(e.message)
    render json: { error: '保存に失敗しました。' }, status: :unprocessable_entity
  end

  private
  def graph_params
    params.require(:graph).permit(:title, :note, :city_id, :thumbnail_url, graph_setting: {})
  end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_action :require_login

  def index
    @q = current_user.graphs.ransack(params[:q])
    @graphs = @q.result(distinct: true).includes(:city).order(created_at: :desc)
    @view_mode = params[:view_mode] || cookies[:view_mode] || "table" # デフォルトはテーブル表示
    cookies[:view_mode] = @view_mode
  end

  def show
    @graph = current_user.graphs.find(params[:id])
  end

  def edit
    @graph = current_user.graphs.find(params[:id])
  end

  def update
    @graph = current_user.graphs.find(params[:id])
    if @graph.update(graph_params)
      redirect_to graph_path(@graph), success: "マイグラフを更新しました"
    else
      flash.now[:error] = "マイグラフの更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    graph = current_user.graphs.find(params[:id])
    graph.destroy!
    redirect_to graphs_path, info: "マイグラフ「#{graph.title}」を削除しました", status: :see_other
  end

  private
  def graph_params
    params.require(:graph).permit(:title, :note)
  end 

  # 追々，Concernを使って共通化する
  def not_authenticated
    redirect_to login_path, error: "ログインが必要です"
  end
end

app/views/graphs/_card_view.html.slim
.flex.flex-wrap.gap-x-6.gap-y-8.justify-start.mt-5
  - graphs.each do |graph|
    .w-56
      = link_to graph_path(graph), class: "block bg-white rounded-lg shadow hover:shadow-lg transform hover:-translate-y-1 transition duration-500" do
        h2.text-xl.font-bold.px-4.py-2.mb-2
          = graph.title
        - if graph.thumbnail?
          = image_tag graph.thumbnail.url, alt: "サムネイル画像", class: "w-full object-cover rounded-b-md"
        - else
          = image_tag "https://placehold.jp/30/d3d3d3/ffffff/300x300.png?text=No+Image", alt: "サムネイル画像", class: "w-full object-cover rounded-b-md"
      .flex.justify-end.mt-2.space-x-2
        = link_to canvas_path(graph: graph.id), class: 'btn btn-sm btn-secondary h-5 p-2' do
          img class="inline-block w-4 h-4 stroke-current" src="/images/edit_chart.svg" alt=""
        = link_to graph_path(graph), data: { turbo_method: :delete, turbo_confirm: "「#{graph.title}」を削除してもよろしいですか？" }, class: 'btn btn-sm btn-accent h-5 p-2' do
          img class="inline-block w-4 h-4 stroke-current" src="/images/trash.svg" alt=""

app/views/graphs/_table_view.html.slim
.shadow-lg.rounded-lg.overflow-x-auto.mx-4.my-5
  table.w-full.text-md.text-left.text-base 
    thead.text-base.bg-primary
      tr.flex
        th.px-6.py-3.scope-col.flex-auto.w-64.text-lg
          | タイトル
        th.px-6.py-3.scope-col.flex-auto.w-32.text-lg
          | 都市
        th.px-6.py-3.scope-col.flex-auto.w-32.text-lg
          | 国・地域
        th.px-6.py-3.text-end.flex-none.w-14
        th.px-6.py-3.text-end.flex-none.w-14
    tbody
      - graphs.each do |graph|
        tr.flex.bg-white.border-b.items-center
          td.px-2.flex-auto.w-64.
            = link_to graph.title, graph_path(graph), class: "text-lg w-full justify-start btn btn-ghost py-0"
          td.px-6.py-4.flex-auto.w-32
            = graph.city.name
          td.px-6.py-4.flex-auto.w-32
            | 日本
          td.px-1.py-2.flex-none.w-14
            = link_to canvas_path(graph: graph.id), class: 'btn btn-secondary h-7 p-2' do
              img class="inline-block w-7 h-7 stroke-current" src="/images/edit_chart.svg" alt=""
          td.px-1.py-2.flex-none.w-14
            = link_to graph_path(graph), data: { turbo_method: :delete, turbo_confirm: "「#{graph.title}」を削除してもよろしいですか？" }, class: 'btn btn-accent h-7 p-2' do
              img class="inline-block w-7 h-7 stroke-current" src="/images/trash.svg" alt=""

app/views/graphs/edit.html.slim
- set_meta_tags title: @graph.title

= form_with model: @graph, local: true do |f|
  .ml-10.mt-5
    .flex.flex-row.justify-between
      .flex
        .mr-5 
          = link_to '戻る', graphs_path, class: 'btn btn-sm btn-grey'

        .ml-5.flex-grow
          = f.text_field :title, class: 'w-80 input input-borderd input-primary p-1 h-8'      
          = f.submit class: 'btn btn-primary btn-sm ml-2 h-8'

      .flex
        .mr-3.justify-end 
          = link_to canvas_path(graph: @graph.id), class: 'btn btn-sm btn-secondary h-4 p-2' do
            img class="inline-block w-4 h-4 stroke-current" src="/images/edit_chart.svg" alt=""      
        .mr-10.justify-end 
          = link_to graph_path(@graph), data: { turbo_method: :delete, turbo_confirm: "「#{@graph.title}」を削除してもよろしいですか？" }, class: 'btn btn-sm btn-accent h-4 p-2' do
            img class="inline-block w-4 h-4 stroke-current" src="/images/trash.svg" alt="" 

  .container.mx-auto.max-w-2xl.my-5
    / ここにマイグラフ
    div class="w-full" id="mygraph-app" data-turbo="false" data-id="#{@graph.id}"
    
    .mt-5.mx-4
      .flex.flex-row.justify-start.items-center.gap-2.mb-3
        h2.text-xl.font-bold メモ
        = f.submit class: 'btn btn-primary btn-sm ml-2 h-8'

      = f.text_area :note, class: 'w-full input input-borderd input-primary p-2 min-h-40'

app/views/graphs/index.html.slim
- set_meta_tags title: 'マイグラフ一覧'

.m-5
  h1.text-3xl.font-bold 
    | #{current_user.username} さんのマイグラフ

  / 検索フォーム
  = search_form_for @q, url: graphs_path do |f|
    .flex.justify-start.space-x-2.my-5
      = f.search_field :title_or_city_name_cont, class: 'input input-primary w-96 h-8 pl-3 pr-2 rounded-lg', placeholder: 'タイトルまたは都市名を入力'
      = f.submit '検索', class: 'btn btn-sm btn-primary h-8'

  .flex.flex-row.justify-end.space-x-1.mr-5
    = link_to graphs_path(view_mode: 'table', q: params[:q]&.to_unsafe_h), class: 'btn btn-sm btn-ghost h-8 p-0 rounded-none' do 
      img class="inline-block w-8 h-8 stroke-current" src="/images/list.svg" alt=""
    = link_to graphs_path(view_mode: 'card', q: params[:q]&.to_unsafe_h), class: 'btn btn-sm btn-ghost h-8 p-0 rounded-none' do
      img class="inline-block w-8 h-8 stroke-current" src="/images/squares-four.svg" alt=""



  - if @view_mode == 'table'
    = render partial: 'table_view', locals: { graphs: @graphs }
  - else
    = render partial: 'card_view', locals: { graphs: @graphs }

app/views/graphs/show.html.slim
- set_meta_tags title: @graph.title

.mx-10.mt-5
  .flex.flex-row.justify-between
    .flex
      .mr-5 
        = link_to '戻る', graphs_path, class: 'btn btn-sm btn-grey'
      h1.text-2xl.font-bold.ml-5
        = @graph.title
      .ml-5 
        = link_to edit_graph_path(@graph) do
          img class="w-4 h-4 p-0" src="/images/edit_icon.svg" alt=""
    .flex
      .mr-3.justify-end 
        = link_to canvas_path(graph: @graph.id), class: 'btn btn-sm btn-secondary h-4 p-2' do
          img class="inline-block w-4 h-4 stroke-current" src="/images/edit_chart.svg" alt=""      
      .mr-10.justify-end 
        = link_to graph_path(@graph), data: { turbo_method: :delete, turbo_confirm: "「#{@graph.title}」を削除してもよろしいですか？" }, class: 'btn btn-sm btn-accent h-4 p-2' do
          img class="inline-block w-4 h-4 stroke-current" src="/images/trash.svg" alt=""      

.container.mx-auto.max-w-2xl.my-8
  / ここにマイグラフ
  div class="w-full" id="mygraph-app" data-turbo="false" data-id="#{@graph.id}"

  .mt-5.mx-4
    .flex.flex-row.justify-start.gap-2.mb-3
      h2.text-xl.font-bold メモ
      = link_to edit_graph_path(@graph) do
        img class="w-4 h-4 p-0" src="/images/edit_icon.svg" alt="" 
    .w-full.border.border-gray-500.rounded-lg.p-2.min-h-40
      = simple_format(@graph.note)

  / 画像表示テスト
  / - if @graph.thumbnail?
  /   .mt-5
  /     = image_tag @graph.thumbnail.url