config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # 単体のページ
  root "static_pages#top"
  get "how_to_use", to: "static_pages#how_to_use"
  get "develop", to: "static_pages#develop"
  get "ogp", to: "static_pages#ogp"
  get "contact", to: "static_pages#contact"
  get "terms_of_service", to: "static_pages#terms_of_service"
  get "privacy_policy", to: "static_pages#privacy_policy"
  get "release_note", to: "static_pages#release_note"

  # ユーザー関連
  resources :users, only: %i[new create destroy]
  
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  post "oauth/callback", to: "oauths#callback" # サービスによってGETとPOSTが異なる場合があるので両方作成
  get "oauth/callback", to: "oauths#callback"
  get "oauth/request/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :profile, only: [:show, :edit, :update], path: 'mypage'  # パスを /mypage, /mypage/edit に
  
  resources :password_resets, only: %i[new create edit update]


  # グラフ作成メイン画面
  get "canvas", to: "canvas#index"
  
  # マイグラフ・マイテンプレート・都市
  resources :graphs, only: %i[index show edit update destroy]
  resources :templates, only: %i[index destroy]
  resources :cities, only: %i[index]

  # API
  namespace :api do
    resources :graphs, only: %i[index show create]
    resources :templates, only: %i[index show create]
    resources :cities, only: %i[index show]
    get "check_login", to: "user_sessions#check_login"
    post "download_counts", to: "download_counts#create"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_before_login_header.html.slim
.navbar.flex.space-x-1.bg-base-300.justify-end.h-12.py-1.px-3
  .flex-1
    .dropdown
      .btn.btn-ghost.p-2 tabindex="0" role="button"
        img class="inline-block w-7 h-7 stroke-current" src="/images/bars_24.svg" alt=""
      ul class="menu menu-lg dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52" tabindex="0"
        li
          = link_to "新規グラフ作成", canvas_path, data: { controller: 'new-graph'}
        li
          = link_to "ユーザー登録", new_user_path
        li
          = link_to "ログイン", login_path
        li
          = link_to "トップページ", root_path

    = link_to "U-ON-ZU!", canvas_path, class: "btn btn-ghost text-2xl", data: { turbo: false }

  .flex-none.gap-x-2
    = link_to "ユーザー登録", new_user_path, class: "btn btn-warning text-md"
    = link_to "ログイン", login_path, class: "btn btn-neutral text-md"
    .dropdown
      .btn.btn-ghost.btn-circle tabindex="0" role="button"
        img class="w-15 h-15 p-0" src="/images/question.svg" alt=""
      ul class="menu menu-lg dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52 origin-top-right right-0" tabindex="0"
        li
          / = link_to "使い方", how_to_use_path
          = link_to "お問い合わせ", contact_path

app/views/shared/_flash_message.html.slim
/ flash_background_colorはhelpersで定義
- flash.each do |message_type, message|
  div class="#{ flash_background_color(message_type) } animate-flash fixed top-16 translate-x-1/2 right-0 z-30 w-fit max-w-[90%] rounded-none py-2 px-6 shadow-xl"
    p.text-sm.font-bold
      = message

app/views/shared/_footer.html.slim
footer.footer.flex.flex-col.items-center.gap-1.px-10.py-1.bg-neutral.text-neutral-content.text-xs
  nav.grid.grid-flow-col.gap-4.m-0 
    = link_to "利用規約", terms_of_service_path, class: "link link-hover"
    = link_to "プライバシーポリシー", privacy_policy_path, class: "link link-hover"
    = link_to "お問い合わせ", contact_path, class: "link link-hover"
    = link_to "リリースノート", release_note_path, class: "link link-hover"
    = link_to "公式 X", "https://x.com/u_on_zu", class: "link link-hover", target: "_blank", rel: "noopener noreferrer"
  aside.m-0
    p.text-center
      | © 2024 U-ON-ZU! All rights reserved.

app/views/shared/_header.html.slim
.navbar.flex.space-x-1.bg-base-300.justify-end.h-12.py-1.px-3
  .flex-1
    .dropdown
      .btn.btn-ghost.p-2 tabindex="0" role="button"
        img class="inline-block w-7 h-7 stroke-current" src="/images/bars_24.svg" alt=""
      ul class="menu menu-lg dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52" tabindex="0"
        li
          = link_to "新規グラフ作成", canvas_path, data: { controller: 'new-graph', turbo: false }
        li
          = link_to "マイグラフ", graphs_path
        li
          = link_to "マイテンプレート", templates_path
        li
          = link_to "マイページ", profile_path
        li
          = link_to "トップページ", root_path
        li
          = link_to "ログアウト", logout_path, data: { turbo_method: :delete }
    div data-turbolinks="false"
      = link_to "U-ON-ZU!", canvas_path, class: "btn btn-ghost text-2xl", data: { turbo: false }

  .flex-none.h-8
    p.font-bold.text-sm.mr-1
      | ログイン中: 
    = link_to profile_path, class: "btn btn-ghost btn-sm py-0 px-2 text-md" do
      = current_user.username
      - if current_user.authentications.present?
        .bg-white.rounded-full
          img class="w-4 h-4" src="https://www.svgrepo.com/show/475656/google-color.svg" loading="lazy" alt="google logo"

    .dropdown
      .btn.btn-ghost.btn-circle tabindex="0" role="button"
        img class="w-15 h-15 p-0" src="/images/question.svg" alt=""
      ul class="menu menu-lg dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52 origin-top-right right-0" tabindex="0"
        li
          / = link_to "使い方", how_to_use_path
          = link_to "お問い合わせ", contact_path