config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # 単体のページ
  root "static_pages#top"
  get "how_to_use", to: "static_pages#how_to_use"
  get "develop", to: "static_pages#develop"
  get "ogp", to: "static_pages#ogp"
  get "contact", to: "static_pages#contact"
  get "terms_of_service", to: "static_pages#terms_of_service"
  get "privacy_policy", to: "static_pages#privacy_policy"
  get "release_note", to: "static_pages#release_note"

  # ユーザー関連
  resources :users, only: %i[new create destroy]
  
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  post "oauth/callback", to: "oauths#callback" # サービスによってGETとPOSTが異なる場合があるので両方作成
  get "oauth/callback", to: "oauths#callback"
  get "oauth/request/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :profile, only: [:show, :edit, :update], path: 'mypage'  # パスを /mypage, /mypage/edit に
  
  resources :password_resets, only: %i[new create edit update]


  # グラフ作成メイン画面
  get "canvas", to: "canvas#index"
  
  # マイグラフ・マイテンプレート・都市
  resources :graphs, only: %i[index show edit update destroy]
  resources :templates, only: %i[index destroy]
  resources :cities, only: %i[index]

  # API
  namespace :api do
    resources :graphs, only: %i[index show create]
    resources :templates, only: %i[index show create]
    resources :cities, only: %i[index show]
    get "check_login", to: "user_sessions#check_login"
    post "download_counts", to: "download_counts#create"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/api/user_sessions_controller.rb
class Api::UserSessionsController < Api::BaseController
  def check_login
    render json: { logged_in: logged_in? }
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # ログイン画面の表示
  # GET /login
  def new
  end

  # ログイン処理
  # POST /login
  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to canvas_path, success: 'ログインしました'
    else
      flash.now[:error] = 'ログインに失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  # ログアウト処理
  # DELETE /logout
  def destroy
    logout
    redirect_to root_path, status: :see_other, info: 'ログアウトしました'
  end
end

app/views/user_sessions/new.html.slim
- set_meta_tags title: 'ログイン'

.container.mx-auto.max-w-xl.my-10
  .w-full.flex.justify-center
    h1.text-3xl.font-bold
      | ログイン

  .container.mx-auto.max-w-md
    .w-full.mt-12.mb-10
      = link_to auth_at_provider_path(provider: :google), class: "btn px-4 py-1 flex items-center gap-2 border border-gray-500 text-slate-700 bg-white" do
        img class="w-4 h-4" src="https://www.svgrepo.com/show/475656/google-color.svg" loading="lazy" alt="google logo"
        span.text-sm Googleアカウントでログイン

    .divider.mb-8
      span.text-gray-700 または

    .justify-center
      = form_with url: login_path do |f|
        .my-5.space-y-3
          = f.label :email, class: 'text-xl font-bold'
          = f.email_field :email, class: 'w-full input input-borderd input-primary'

        .my-5.space-y-3
          = f.label :password, class: 'text-xl font-bold'
          = f.password_field :password, class: 'w-full input input-borderd input-primary'

        .my-10.flex.justify-center
          = f.submit 'ログイン', class: 'btn btn-neutral', data: { disable_with: 'ログイン' }
  
  .w-full.text-end
    p.text-md.mb-3
      = link_to 'パスワードをお忘れの方', new_password_reset_path, class: 'underline'
    p.text-md.mb-3
      = link_to 'アカウントをまだお持ちでない方', new_user_path, class: 'underline'